-- V1 초기 스키마(베이스라인). 현재 JPA 엔티티가 생성하는 스키마를 그대로 고정한다.
-- 생성법: 빈 PostgreSQL에 ddl-auto=create로 만든 뒤 pg_dump -s로 추출. 이후 스키마 변경은 V2 이상으로만 추가하고,
-- 운영은 ddl-auto: validate로 엔티티와 이 스키마의 일치를 검증한다.

CREATE TABLE public.artifact_section_source_experiences (
    source_order integer NOT NULL,
    artifact_section_id uuid NOT NULL,
    source_experience_id character varying(255) NOT NULL
);

CREATE TABLE public.artifact_sections (
    section_order integer,
    id uuid NOT NULL,
    version_id uuid NOT NULL,
    definition_key character varying(100) NOT NULL,
    content character varying(10000) NOT NULL,
    section_kind character varying(255) NOT NULL,
    status character varying(255) NOT NULL,
    CONSTRAINT artifact_sections_section_kind_check CHECK (((section_kind)::text = ANY ((ARRAY['SUMMARY'::character varying, 'CAREER'::character varying, 'EXPERIENCE_NARRATIVE'::character varying])::text[]))),
    CONSTRAINT artifact_sections_status_check CHECK (((status)::text = ANY ((ARRAY['GENERATING'::character varying, 'GENERATED'::character varying, 'GENERATION_FAILED'::character varying, 'VALIDATION_FAILED'::character varying])::text[])))
);

CREATE TABLE public.artifact_template_snapshot_sections (
    required boolean NOT NULL,
    snapshot_section_order integer NOT NULL,
    artifact_id uuid NOT NULL,
    definition_key character varying(100) NOT NULL,
    name character varying(100) NOT NULL,
    section_kind character varying(255) NOT NULL,
    CONSTRAINT artifact_template_snapshot_sections_section_kind_check CHECK (((section_kind)::text = ANY ((ARRAY['SUMMARY'::character varying, 'CAREER'::character varying, 'EXPERIENCE_NARRATIVE'::character varying])::text[])))
);

CREATE TABLE public.artifacts (
    active_version_id uuid NOT NULL,
    id uuid NOT NULL,
    owner_id uuid NOT NULL,
    target_recruit_direction character varying(200) NOT NULL,
    kind character varying(255) NOT NULL,
    target_company_name character varying(255),
    target_job_title character varying(255),
    CONSTRAINT artifacts_kind_check CHECK (((kind)::text = ANY ((ARRAY['RESUME'::character varying, 'PORTFOLIO'::character varying])::text[])))
);

CREATE TABLE public.experience_records (
    period_end date,
    period_start date,
    id uuid NOT NULL,
    owner_id uuid NOT NULL,
    action character varying(2000),
    result character varying(2000),
    situation character varying(2000),
    body character varying(5000) NOT NULL,
    title character varying(255) NOT NULL,
    type character varying(255) NOT NULL,
    CONSTRAINT experience_records_type_check CHECK (((type)::text = ANY ((ARRAY['PROJECT'::character varying, 'JOB'::character varying, 'EXTRACURRICULAR'::character varying, 'AWARD'::character varying, 'LEARNING'::character varying])::text[])))
);

CREATE TABLE public.experience_skill_tags (
    experience_record_id uuid NOT NULL,
    skill_tag character varying(255) NOT NULL
);

CREATE TABLE public.fact_groundings (
    grounding_order integer,
    id bigint NOT NULL,
    artifact_section_id uuid NOT NULL,
    source_experience_id uuid NOT NULL,
    token character varying(500) NOT NULL,
    evidence_text character varying(2000) NOT NULL,
    kind character varying(255) NOT NULL,
    CONSTRAINT fact_groundings_kind_check CHECK (((kind)::text = ANY ((ARRAY['NUMERIC'::character varying, 'PROPER_NOUN'::character varying])::text[])))
);

ALTER TABLE public.fact_groundings ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.fact_groundings_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

CREATE TABLE public.generation_quota_counters (
    count integer NOT NULL,
    quota_date date NOT NULL,
    id uuid NOT NULL,
    scope_key character varying(255) NOT NULL
);

CREATE TABLE public.resume_template_sections (
    required boolean NOT NULL,
    section_order integer NOT NULL,
    resume_template_id uuid NOT NULL,
    name character varying(100) NOT NULL,
    "character" character varying(255) NOT NULL,
    CONSTRAINT resume_template_sections_character_check CHECK ((("character")::text = ANY ((ARRAY['SUMMARY'::character varying, 'CAREER'::character varying])::text[])))
);

CREATE TABLE public.resume_templates (
    id uuid NOT NULL,
    owner_id uuid NOT NULL,
    name character varying(100) NOT NULL
);

CREATE TABLE public.target_briefs (
    id uuid NOT NULL,
    owner_id uuid NOT NULL,
    recruit_direction character varying(5000) NOT NULL,
    company_name character varying(255),
    job_title character varying(255)
);

CREATE TABLE public.users (
    id uuid NOT NULL,
    email character varying(255) NOT NULL,
    password_hash character varying(255) NOT NULL,
    time_zone character varying(255)
);

CREATE TABLE public.versions (
    version_order integer,
    created_at timestamp(6) with time zone NOT NULL,
    artifact_id uuid NOT NULL,
    id uuid NOT NULL
);

ALTER TABLE ONLY public.artifact_section_source_experiences
    ADD CONSTRAINT artifact_section_source_experiences_pkey PRIMARY KEY (source_order, artifact_section_id);

ALTER TABLE ONLY public.artifact_sections
    ADD CONSTRAINT artifact_sections_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.artifact_template_snapshot_sections
    ADD CONSTRAINT artifact_template_snapshot_sections_pkey PRIMARY KEY (snapshot_section_order, artifact_id);

ALTER TABLE ONLY public.artifacts
    ADD CONSTRAINT artifacts_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.experience_records
    ADD CONSTRAINT experience_records_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fact_groundings
    ADD CONSTRAINT fact_groundings_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.generation_quota_counters
    ADD CONSTRAINT generation_quota_counters_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.resume_template_sections
    ADD CONSTRAINT resume_template_sections_pkey PRIMARY KEY (section_order, resume_template_id);

ALTER TABLE ONLY public.resume_templates
    ADD CONSTRAINT resume_templates_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.target_briefs
    ADD CONSTRAINT target_briefs_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.generation_quota_counters
    ADD CONSTRAINT uk_quota_scope_date UNIQUE (scope_key, quota_date);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_email_key UNIQUE (email);

ALTER TABLE ONLY public.users
    ADD CONSTRAINT users_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.versions
    ADD CONSTRAINT versions_pkey PRIMARY KEY (id);

ALTER TABLE ONLY public.fact_groundings
    ADD CONSTRAINT fk1mnddym9dv85erm8fuvadca6y FOREIGN KEY (artifact_section_id) REFERENCES public.artifact_sections(id);

ALTER TABLE ONLY public.artifact_section_source_experiences
    ADD CONSTRAINT fk3xiis2yhper8ab12ifn1a195h FOREIGN KEY (artifact_section_id) REFERENCES public.artifact_sections(id);

ALTER TABLE ONLY public.experience_skill_tags
    ADD CONSTRAINT fk8omh6vg7gnqr336vp7h9vdsch FOREIGN KEY (experience_record_id) REFERENCES public.experience_records(id);

ALTER TABLE ONLY public.artifact_template_snapshot_sections
    ADD CONSTRAINT fkad2s4fsu2kbm3wk2di6u1lvn3 FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id);

ALTER TABLE ONLY public.resume_template_sections
    ADD CONSTRAINT fkb8c5gxw3q49fgpkst59fc1d86 FOREIGN KEY (resume_template_id) REFERENCES public.resume_templates(id);

ALTER TABLE ONLY public.artifact_sections
    ADD CONSTRAINT fklme7ai6maac4q02pck9ddltic FOREIGN KEY (version_id) REFERENCES public.versions(id);

ALTER TABLE ONLY public.versions
    ADD CONSTRAINT fkqeb33i721jht6cfy6anex09u5 FOREIGN KEY (artifact_id) REFERENCES public.artifacts(id);
